name: Push Checks
run-name: Check - ${{ github.event.head_commit.message }}
on: push
jobs:
    call_test_and_build:
        name: Call test and build
        uses: ./.github/workflows/test_and_build.yaml
